SQL> SET ECHO ON
SQL> DROP TABLE ADDRESS
CASCADE CONSTRAINTS;

Table ADDRESS dropped.

SQL> DROP TABLE CARBODY
CASCADE CONSTRAINTS;

Table CARBODY dropped.

SQL> DROP TABLE CARCOLOR
CASCADE CONSTRAINTS;

Table CARCOLOR dropped.

SQL> DROP TABLE CARFEATURES
CASCADE CONSTRAINTS;

Table CARFEATURES dropped.

SQL> DROP TABLE CARMAKER
CASCADE CONSTRAINTS;

Table CARMAKER dropped.

SQL> DROP TABLE CARMODEL
CASCADE CONSTRAINTS;

Table CARMODEL dropped.

SQL> DROP TABLE CARTRANSMISSION
CASCADE CONSTRAINTS;

Table CARTRANSMISSION dropped.

SQL> DROP TABLE CUSTOMER
CASCADE CONSTRAINTS;

Table CUSTOMER dropped.

SQL> DROP TABLE DRIVETRAIN
CASCADE CONSTRAINTS;

Table DRIVETRAIN dropped.

SQL> DROP TABLE LICENSE_TAX_INSUR
CASCADE CONSTRAINTS;

Table LICENSE_TAX_INSUR dropped.

SQL> DROP TABLE MOTOR
CASCADE CONSTRAINTS;

Table MOTOR dropped.

SQL> DROP TABLE SALE
CASCADE CONSTRAINTS;

Table SALE dropped.

SQL> DROP TABLE SALESPERSON
CASCADE CONSTRAINTS;

Table SALESPERSON dropped.

SQL> DROP TABLE SATISFACTION
CASCADE CONSTRAINTS;

Table SATISFACTION dropped.

SQL> DROP TABLE VEHICLE
CASCADE CONSTRAINTS;

Table VEHICLE dropped.

SQL> SET ECHO ON
SQL> DROP TABLE ADDRESS
CASCADE CONSTRAINTS;

SQL> -- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
SQL> --   at:        2016-11-05 15:18:45 EDT
SQL> --   site:      Oracle Database 11g
SQL> --   type:      Oracle Database 11g
SQL> CREATE TABLE DriveTrain
  (
    DrivetrainID NUMBER NOT NULL ,
    Drivetrain   CHAR (256)
  ) ;

Table DRIVETRAIN created.

SQL> ALTER TABLE DriveTrain ADD CONSTRAINT DriveTrain_PK PRIMARY KEY ( DrivetrainID ) ;

Table DRIVETRAIN altered.

SQL> CREATE TABLE License_Tax_Insur
  (
    StateTax       NUMBER ,
    LicenseFee     NUMBER ,
    ProofInsurance CHAR (1) ,
    AddiFeeID      NUMBER NOT NULL
  ) ;

Table LICENSE_TAX_INSUR created.

SQL> ALTER TABLE License_Tax_Insur ADD CHECK ( ProofInsurance IN ('N', 'Y', 'n', 'y')) ;

Table LICENSE_TAX_INSUR altered.

SQL> ALTER TABLE License_Tax_Insur ADD CONSTRAINT License_Tax_Insur_PK PRIMARY KEY ( AddiFeeID ) ;

Table LICENSE_TAX_INSUR altered.

SQL> CREATE TABLE Motor
  ( MotorID NUMBER NOT NULL , Motor CHAR (256)
  ) ;

Table MOTOR created.

SQL> ALTER TABLE Motor ADD CONSTRAINT Motor_PK PRIMARY KEY ( MotorID ) ;

Table MOTOR altered.

SQL> CREATE TABLE Transmission
  (
    TransmissionID   NUMBER NOT NULL ,
    TransmissionType CHAR (256)
  ) ;

Table TRANSMISSION created.

SQL> ALTER TABLE Transmission ADD CONSTRAINT carTransmission_PK PRIMARY KEY ( TransmissionID ) ;

Table TRANSMISSION altered.

SQL> CREATE TABLE address
  (
    StreetName   CHAR (256) ,
    StreetNumber NUMBER ,
    City         CHAR (256) ,
    State        CHAR (256) ,
    Country      CHAR (256) ,
    AddressID    NUMBER NOT NULL
  ) ;

Table ADDRESS created.

SQL> ALTER TABLE address ADD CONSTRAINT address_PK PRIMARY KEY ( AddressID ) ;

Table ADDRESS altered.

SQL> CREATE TABLE carBody
  (
    VehicleBodyID NUMBER NOT NULL ,
    VehicleBody   CHAR (256)
  ) ;

Table CARBODY created.

SQL> ALTER TABLE carBody ADD CONSTRAINT carBody_PK PRIMARY KEY ( VehicleBodyID ) ;

Table CARBODY altered.

SQL> CREATE TABLE carColor
  ( ColorID NUMBER NOT NULL , Color CHAR (256)
  ) ;

Table CARCOLOR created.

SQL> ALTER TABLE carColor ADD CONSTRAINT carColor_PK PRIMARY KEY ( ColorID ) ;

Table CARCOLOR altered.

SQL> CREATE TABLE carFeatures
  ( FeatureID NUMBER NOT NULL , Feature CHAR (256)
  ) ;

Table CARFEATURES created.

SQL> ALTER TABLE carFeatures ADD CONSTRAINT carFeatures_PK PRIMARY KEY ( FeatureID ) ;

Table CARFEATURES altered.

SQL> CREATE TABLE carMaker
  (
    MakerID          NUMBER NOT NULL ,
    Maker            CHAR (256) ,
    carModel_ModelID NUMBER NOT NULL
  ) ;

Table CARMAKER created.

SQL> CREATE UNIQUE INDEX carMaker__IDX ON carMaker
  (
    carModel_ModelID ASC
  )
  ;

Unique index CARMAKER__IDX created.

SQL> ALTER TABLE carMaker ADD CONSTRAINT carMaker_PK PRIMARY KEY ( MakerID ) ;

Table CARMAKER altered.

SQL> CREATE TABLE carModel
  (
    ModelID    NUMBER NOT NULL ,
    ModelMaker NUMBER ,
    Model      CHAR (256)
  ) ;

Table CARMODEL created.

SQL> ALTER TABLE carModel ADD CONSTRAINT carModel_PK PRIMARY KEY ( ModelID ) ;

Table CARMODEL altered.

SQL> CREATE TABLE customer
  (
    CustomerID                NUMBER NOT NULL ,
    Loan                      NUMBER ,
    FName                     CHAR (256) ,
    LName                     CHAR (256) ,
    SpendLevel                NUMBER ,
    Years                     NUMBER ,
    Zip                       NUMBER ,
    address_AddressID         NUMBER NOT NULL ,
    salesperson_SalesPersonID NUMBER NOT NULL ,
    Phone                     NUMBER ,
    email                     CHAR (256)
  ) ;

Table CUSTOMER created.

SQL> CREATE INDEX customer__IDX ON customer
  ( address_AddressID ASC
  ) ;

Index CUSTOMER__IDX created.

SQL> CREATE INDEX customer__IDXv1 ON customer
  ( salesperson_SalesPersonID ASC
  ) ;

Index CUSTOMER__IDXV1 created.

SQL> ALTER TABLE customer ADD CONSTRAINT customer_PK PRIMARY KEY ( CustomerID ) ;

Table CUSTOMER altered.

SQL> CREATE TABLE sale
  (
    CurrentMileage              NUMBER ,
    Customization               NUMBER ,
    Financing                   NUMBER ,
    Warranty                    NUMBER ,
    TaxesFees                   NUMBER ,
    TotalPrice                  NUMBER ,
    CostofVehicle               NUMBER ,
    SaleID                      NUMBER NOT NULL ,
    License_Tax_Insur_AddiFeeID NUMBER NOT NULL ,
    vehicle_VehicleID           NUMBER NOT NULL ,
    salesperson_SalesPersonID   NUMBER NOT NULL
  ) ;

Table SALE created.

SQL> CREATE UNIQUE INDEX sale__IDX ON sale
  (
    License_Tax_Insur_AddiFeeID ASC
  )
  ;

Unique index SALE__IDX created.

SQL> ALTER TABLE sale ADD CONSTRAINT sale_PK PRIMARY KEY ( SaleID ) ;

Table SALE altered.

SQL> CREATE TABLE salesperson
  (
    CR                NUMBER ,
    Discount          NUMBER ,
    FName             CHAR (256) ,
    SalesPersonID     NUMBER NOT NULL ,
    LName             CHAR (256) ,
    Manager           NUMBER ,
    Pay               NUMBER ,
    Perform           NUMBER ,
    Sales             NUMBER ,
    SickDays          NUMBER ,
    Status            CHAR (256) ,
    Title             CHAR (256) ,
    VacDays           NUMBER ,
    Years             NUMBER ,
    Zip               NUMBER ,
    address_AddressID NUMBER NOT NULL ,
    Phone             NUMBER ,
    email             CHAR (256)
  ) ;

Table SALESPERSON created.

SQL> ALTER TABLE salesperson ADD CHECK ( CR BETWEEN 0.00 AND 100.00) ;

Table SALESPERSON altered.

SQL> ALTER TABLE salesperson ADD CHECK ( Discount BETWEEN 0.00 AND 100.00) ;

Table SALESPERSON altered.

SQL> CREATE UNIQUE INDEX salesperson__IDX ON salesperson ( address_AddressID ASC ) ;

Unique index SALESPERSON__IDX created.

SQL> ALTER TABLE salesperson ADD CONSTRAINT salesperson_PK PRIMARY KEY ( SalesPersonID ) ;

Table SALESPERSON altered.

SQL> CREATE TABLE satisfaction
  (
    Car                 NUMBER ,
    Dealership          NUMBER ,
    Salesperson         NUMBER ,
    customer_CustomerID NUMBER NOT NULL
  ) ;

Table SATISFACTION created.

SQL> CREATE UNIQUE INDEX satisfaction__IDX ON satisfaction
  (
    customer_CustomerID ASC
  )
  ;

Unique index SATISFACTION__IDX created.

SQL> CREATE TABLE vehicle
  (
    Delivered                      DATE ,
    Doors                          NUMBER ,
    VehicleID                      NUMBER NOT NULL ,
    MileageCurrent                 NUMBER ,
    MileageOrig                    NUMBER ,
    NEW                            CHAR (1) ,
    Price                          NUMBER ,
    ListPrice                      NUMBER ,
    Status                         NUMBER ,
    Weight                         INTEGER ,
    YEAR                           INTEGER ,
    carColor_ColorID               NUMBER NOT NULL ,
    carFeatures_FeatureID          NUMBER NOT NULL ,
    carModel_ModelID               NUMBER NOT NULL ,
    salesperson_SalesPersonID      NUMBER NOT NULL ,
    carTransmission_TransmissionID NUMBER NOT NULL ,
    carBody_VehicleBodyID          NUMBER NOT NULL ,
    DriveTrain_DrivetrainID        NUMBER NOT NULL ,
    Motor_MotorID                  NUMBER NOT NULL
  ) ;

Table VEHICLE created.

SQL> ALTER TABLE vehicle ADD CHECK ( NEW IN ('N', 'Y', 'n', 'y')) ;

Table VEHICLE altered.

SQL> CREATE INDEX vehicle__IDX ON vehicle
  ( carColor_ColorID ASC
  ) ;

Index VEHICLE__IDX created.

SQL> CREATE INDEX vehicle__IDXv1 ON vehicle
  (
    carTransmission_TransmissionID ASC
  ) ;

Index VEHICLE__IDXV1 created.

SQL> CREATE INDEX vehicle__IDXv2 ON vehicle
  ( carBody_VehicleBodyID ASC
  ) ;

Index VEHICLE__IDXV2 created.

SQL> CREATE INDEX vehicle__IDXv3 ON vehicle
  ( DriveTrain_DrivetrainID ASC
  ) ;

Index VEHICLE__IDXV3 created.

SQL> CREATE INDEX vehicle__IDXv4 ON vehicle
  ( Motor_MotorID ASC
  ) ;

Index VEHICLE__IDXV4 created.

SQL> CREATE INDEX vehicle__IDXv5 ON vehicle
  ( carFeatures_FeatureID ASC
  ) ;

Index VEHICLE__IDXV5 created.

SQL> CREATE INDEX vehicle__IDXv6 ON vehicle
  ( carModel_ModelID ASC
  ) ;

Index VEHICLE__IDXV6 created.

SQL> ALTER TABLE vehicle ADD CONSTRAINT vehicle_PK PRIMARY KEY ( VehicleID ) ;

Table VEHICLE altered.

SQL> ALTER TABLE carMaker ADD CONSTRAINT carMaker_carModel_FK FOREIGN KEY ( carModel_ModelID ) REFERENCES carModel ( ModelID ) ;

Table CARMAKER altered.

SQL> ALTER TABLE customer ADD CONSTRAINT customer_address_FK FOREIGN KEY ( address_AddressID ) REFERENCES address ( AddressID ) ;

Table CUSTOMER altered.

SQL> ALTER TABLE customer ADD CONSTRAINT customer_salesperson_FK FOREIGN KEY ( salesperson_SalesPersonID ) REFERENCES salesperson ( SalesPersonID ) ;

Table CUSTOMER altered.

SQL> ALTER TABLE sale ADD CONSTRAINT sale_License_Tax_Insur_FK FOREIGN KEY ( License_Tax_Insur_AddiFeeID ) REFERENCES License_Tax_Insur ( AddiFeeID ) ;

Table SALE altered.

SQL> ALTER TABLE sale ADD CONSTRAINT sale_salesperson_FK FOREIGN KEY ( salesperson_SalesPersonID ) REFERENCES salesperson ( SalesPersonID ) ;

Table SALE altered.

SQL> ALTER TABLE sale ADD CONSTRAINT sale_vehicle_FK FOREIGN KEY ( vehicle_VehicleID ) REFERENCES vehicle ( VehicleID ) ;

Table SALE altered.

SQL> ALTER TABLE salesperson ADD CONSTRAINT salesperson_address_FK FOREIGN KEY ( address_AddressID ) REFERENCES address ( AddressID ) ;

Table SALESPERSON altered.

SQL> ALTER TABLE satisfaction ADD CONSTRAINT satisfaction_customer_FK FOREIGN KEY ( customer_CustomerID ) REFERENCES customer ( CustomerID ) ;

Table SATISFACTION altered.

SQL> ALTER TABLE vehicle ADD CONSTRAINT vehicle_DriveTrain_FK FOREIGN KEY ( DriveTrain_DrivetrainID ) REFERENCES DriveTrain ( DrivetrainID ) ;

Table VEHICLE altered.

SQL> ALTER TABLE vehicle ADD CONSTRAINT vehicle_Motor_FK FOREIGN KEY ( Motor_MotorID ) REFERENCES Motor ( MotorID ) ;

Table VEHICLE altered.

SQL> ALTER TABLE vehicle ADD CONSTRAINT vehicle_carBody_FK FOREIGN KEY ( carBody_VehicleBodyID ) REFERENCES carBody ( VehicleBodyID ) ;

Table VEHICLE altered.

SQL> ALTER TABLE vehicle ADD CONSTRAINT vehicle_carColor_FK FOREIGN KEY ( carColor_ColorID ) REFERENCES carColor ( ColorID ) ;

Table VEHICLE altered.

SQL> ALTER TABLE vehicle ADD CONSTRAINT vehicle_carFeatures_FK FOREIGN KEY ( carFeatures_FeatureID ) REFERENCES carFeatures ( FeatureID ) ;

Table VEHICLE altered.

SQL> ALTER TABLE vehicle ADD CONSTRAINT vehicle_carModel_FK FOREIGN KEY ( carModel_ModelID ) REFERENCES carModel ( ModelID ) ;

Table VEHICLE altered.

SQL> ALTER TABLE vehicle ADD CONSTRAINT vehicle_carTransmission_FK FOREIGN KEY ( carTransmission_TransmissionID ) REFERENCES Transmission ( TransmissionID ) ;

Table VEHICLE altered.

SQL> ALTER TABLE vehicle ADD CONSTRAINT vehicle_salesperson_FK FOREIGN KEY ( salesperson_SalesPersonID ) REFERENCES salesperson ( SalesPersonID ) ;

Table VEHICLE altered.

SQL> -- Oracle SQL Developer Data Modeler Summary Report: 
SQL> -- 
SQL> -- CREATE TABLE                            15
SQL> -- CREATE INDEX                            13
SQL> -- ALTER TABLE                             34
SQL> -- CREATE VIEW                              0
SQL> -- ALTER VIEW                               0
SQL> -- CREATE PACKAGE                           0
SQL> -- CREATE PACKAGE BODY                      0
SQL> -- CREATE PROCEDURE                         0
SQL> -- CREATE FUNCTION                          0
SQL> -- CREATE TRIGGER                           0
SQL> -- ALTER TRIGGER                            0
SQL> -- CREATE COLLECTION TYPE                   0
SQL> -- CREATE STRUCTURED TYPE                   0
SQL> -- CREATE STRUCTURED TYPE BODY              0
SQL> -- CREATE CLUSTER                           0
SQL> -- CREATE CONTEXT                           0
SQL> -- CREATE DATABASE                          0
SQL> -- CREATE DIMENSION                         0
SQL> -- CREATE DIRECTORY                         0
SQL> -- CREATE DISK GROUP                        0
SQL> -- CREATE ROLE                              0
SQL> -- CREATE ROLLBACK SEGMENT                  0
SQL> -- CREATE SEQUENCE                          0
SQL> -- CREATE MATERIALIZED VIEW                 0
SQL> -- CREATE SYNONYM                           0
SQL> -- CREATE TABLESPACE                        0
SQL> -- CREATE USER                              0
SQL> -- 
SQL> -- DROP TABLESPACE                          0
SQL> -- DROP DATABASE                            0
SQL> -- 
SQL> -- REDACTION POLICY                         0
SQL> -- 
SQL> -- ORDS DROP SCHEMA                         0
SQL> -- ORDS ENABLE SCHEMA                       0
SQL> -- ORDS ENABLE OBJECT                       0
SQL> -- 
SQL> -- ERRORS                                   0
SQL> -- WARNINGS                                 0
